
expressions:
  explist:
    - idx: 1
      regex: Please create a processor group in name "(.+)"\.
      task: createProcessorGroup
      number: 1
    - idx: 2
      regex: Please remove the processor group in name "(.+)"\.
      task: deleteProcessorGroup
      number: 1

nlu:
  chatgpt:
    url: https://ssgenaius-backend.azurewebsites.net
    dummy: "[{\"type\": \"GetFile\",\"parameters\": {\"Input Directory\": \"D:\\\\testfolder\\\\input\",\"File Filter\": \".*\\.txt\"}},{\"type\": \"EncryptContent\",\"parameters\": {\"Encryption Algorithm\": \"PGP\",\"Password\": \"your_password_here\"}},{\"type\": \"PutFile\",\"parameters\": {\"Directory\": \"D:\\\\testfolder\\\\output\"}}]"
    skip: false
    timeout: 300000
  target: chatgpt_ss
#  target: regular_expression

chatgpt:
  prompt:
    template: "Now I'm using a data ETL tool called Apache nifi. Users are able to create processors to compose a workflow to acquire, transform and export data. Please help me to make a design of the workflow according to my intention. I want you to translate my idea into a suggestion about what processors should be put into the workflow.  I need you provide your proposal in a JSON array, having each object of that array representing a processor in the same sequence as the processors along the workflow. Each JSON object should follow this format \"{type: 'ProcessorName', parameters: {parameter name:'parameter value'}}\". For example, if I want to move a file from D:\\testfolder\\input to D:\\testfolder\\output without any transformation, I want you to provide me \"[{type:'GetFile',parameters:{Input Directory:'D:\\testfolder\\input'}},{type:'PutFile',parameters:{Directory:'D:\\testfolder\\input'}}]\".\\r\\nNow, let's do it. \\n %s \\n What is your suggestion? Return nothing else but the JSON array please."
