server:
  port: 8001

spring:
  application:
    name: api-supporter-service
  servlet:
    multipart:
      max-file-size: 128KB
      max-request-size: 128KB
  config:
    import:
      - classpath:application-nlu.yml
      - classpath:application-nifi.yml


log4j:
  rootLogger: DEBUG, stdout


